Importation des Bibliothèques

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuration de l'affichage pour voir toutes les colonnes
pd.set_option('display.max_columns', None)

Chargement des Datasets

In [2]:
# Energy Mix
df_energy = pd.read_csv('../data_raw/energy mix.csv')

In [2]:
# CO2 Emissions
df_co2 = pd.read_csv('../data_raw/owid-co2-data.csv')

In [16]:
# GDP avec saut des lignes de métadonnées
df_gdp = pd.read_csv('../data_raw/GDP_total.csv', skiprows=4)

In [2]:
# Population avec saut des lignes de métadonnées
df_pop = pd.read_csv('../data_raw/Population_total.csv', skiprows=4)

In [13]:
df_access = pd.read_csv('../data_raw/electricity access.csv', skiprows=4)

EDA - Dimensions et Aperçu

In [8]:
#Energy Mix
print(f"Dimensions Energy Mix : {df_energy.shape}")
df_energy.head(5)

Dimensions Energy Mix : (7859, 11)

,Entity,Code,Year,Oil,Gas,Coal,Hydropower,Solar,Wind,Nuclear,Other renewables
0,Africa,NaN,1965,341.07257,9.571930,323.49615,13.905635,0.0,0.0,0.0,0.0
1,Africa,NaN,1966,369.46457,10.698092,323.12222,15.510004,0.0,0.0,0.0,0.0
2,Africa,NaN,1967,368.28156,10.573844,330.29160,16.190636,0.0,0.0,0.0,0.0
3,Africa,NaN,1968,389.57162,10.717145,343.51288,18.938341,0.0,0.0,0.0,0.0
4,Africa,NaN,1969,397.37260,12.520175,346.64288,22.100890,0.0,0.0,0.0,0.0

In [6]:
# CO2 Emissions
print(f"Dimensions CO2 Data : {df_co2.shape}")
df_co2.head(5)

Dimensions CO2 Data : (50411, 79)

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,co2_including_luc_growth_prct,co2_including_luc_per_capita,co2_including_luc_per_gdp,co2_including_luc_per_unit_energy,co2_per_capita,co2_per_gdp,co2_per_unit_energy,coal_co2,coal_co2_per_capita,consumption_co2,consumption_co2_per_capita,consumption_co2_per_gdp,cumulative_cement_co2,cumulative_co2,cumulative_co2_including_luc,cumulative_coal_co2,cumulative_flaring_co2,cumulative_gas_co2,cumulative_luc_co2,cumulative_oil_co2,cumulative_other_co2,energy_per_capita,energy_per_gdp,flaring_co2,flaring_co2_per_capita,gas_co2,gas_co2_per_capita,ghg_excluding_lucf_per_capita,ghg_per_capita,land_use_change_co2,land_use_change_co2_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,oil_co2,oil_co2_per_capita,other_co2_per_capita,other_industry_co2,primary_energy_consumption,share_global_cement_co2,share_global_co2,share_global_co2_including_luc,share_global_coal_co2,share_global_cumulative_cement_co2,share_global_cumulative_co2,share_global_cumulative_co2_including_luc,share_global_cumulative_coal_co2,share_global_cumulative_flaring_co2,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# GDP 
print(f"Dimensions GDP : {df_gdp.shape}")
df_gdp.head(5)

Dimensions GDP : (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.055866e+08,4.877095e+08,5.966480e+08,6.955307e+08,7.648045e+08,8.720670e+08,9.586592e+08,1.083240e+09,1.245810e+09,1.320670e+09,1.379888e+09,1.531844e+09,1.665363e+09,1.722905e+09,1.873453e+09,1.896457e+09,1.961844e+09,2.044112e+09,2.254831e+09,2.360017e+09,2.469783e+09,2.677641e+09,2.843025e+09,2.553793e+09,2.453597e+09,2.637859e+09,2.615208e+09,2.727849e+09,2.790850e+09,2.962907e+09,2.983637e+09,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,3.692725e+10,3.844416e+10,4.174200e+10,4.704852e+10,4.759391e+10,5.218869e+10,5.672606e+10,7.308360e+10,8.953598e+10,9.529575e+10,9.600642e+10,1.092082e+11,1.240834e+11,1.421000e+11,1.784723e+11,1.851090e+11,1.783555e+11,1.857555e+11,1.700385e+11,1.493352e+11,1.605535e+11,1.901752e+11,2.073689e+11,2.206134e+11,2.563831e+11,2.769185e+11,2.411883e+11,2.399812e+11,2.434775e+11,2.733270e+11,2.734276e+11,2.882707e+11,2.687281e+11,2.653210e+11,2.870420e+11,2.608500e+11,2.697460e+11,3.581161e+11,4.459748e+11,5.215620e+11,5.875005e+11,6.749999e+11,7.267704e+11,7.269216e+11,8.638221e+11,9.598225e+11,9.692657e+11,9.813089e+11,9.988362e+11,9.100020e+11,8.318681e+11,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.521418e+09,2.813572e+09,3.825701e+09,4.520947e+09,5.224897e+09,6.203257e+09,6.971758e+09,9.747886e+09,1.010930e+10,1.241615e+10,1.585667e+10,1.780510e+10,1.990733e+10,2.014642e+10,2.049713e+10,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,1.803395e+10,1.649354e+10,1.702260e+10,1.930119e+10,2.669692e+10,2.449679e+10,2.948943e+10,3.689063e+10,4.968722e+10,5.728012e+10,6.838555e+10,7.178950e+10,7.877808e+10,9.668106e+10,1.214460e+11,2.176065e+11,1.962649e+11,1.514214e+11,1.313731e+11,1.380051e+11,1.095178e+11,1.126411e+11,1.117703e+11,1.045774e+11,1.242778e+11,1.307943e+11,1.254494e+11,1.305471e+11,1.353508e+11,2.078439e+11,2.635636e+11,2.764600e+11,2.971265e+11,1.401191e+11,1.427002e+11,1.507144e+11,1.801292e+11,2.086465e+11,2.579393e+11,3.165157e+11,4.020774e+11,4.709476e+11,5.742598e+11,5.150371e+11,6.057943e+11,6.911334e+11,7.480300e+11,8.441804e+11,9.040719e+11,7.780221e+11,7.000282e+11,6.940513e+11,7.778403e+11,1.026996e+12,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.930503e+09,5.550483e+09,5.550483e+09,5.784342e+09,6.131475e+09,7.554065e+09,7.072536e+09,8.084412e+09,8.769837e+09,1.020178e+10,1.122952e+10,1.060378e+10,8.307811e+09,5.768720e+09,4.438321e+09,5.538749e+09,7.526422e+09,7.648380e+09,6.506222e+09,6.152923e+09,9.129595e+09,8.936079e+09,1.731151e+10,2.034213e+10,2.699798e+10,4.139664e+10,5.865366e+10,7.303782e+10,9.879043e+10,8.170518e+10,9.554692e+10,1.255516e+11,1.435729e+11,1.488452e+11,1.534499e+11,1.025431e+11,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11,NaN

In [3]:
# Population
print(f"Dimensions Population : {df_pop.shape}")
df_pop.head(5)

Dimensions Population : (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,58694.0,58990.0,59069.0,59052.0,58950.0,58781.0,58047.0,58299.0,58349.0,58295.0,58368.0,58580.0,58776.0,59191.0,59909.0,60563.0,61276.0,62228.0,62901.0,61728.0,59931.0,59159.0,59331.0,60443.0,62753.0,65896.0,69005.0,73685.0,77595.0,79805.0,83021.0,86301.0,88451.0,89659.0,90588.0,91439.0,92074.0,93128.0,95138.0,97635.0,99405.0,100150.0,100917.0,101604.0,101838.0,102591.0,104110.0,105675.0,106807.0,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,153281203.0,157704381.0,162329396.0,167088245.0,171984985.0,177022314.0,182126556.0,187524135.0,193186642.0,198914573.0,204802976.0,210680842.0,217074286.0,223974122.0,230792729.0,238043099.0,245822010.0,253644643.0,261458202.0,269450407.0,277621771.0,286067346.0,294498625.0,302939121.0,311748681.0,320442961.0,329082707.0,338324002.0,347441809.0,356580375.0,366138524.0,375646235.0,385505757.0,395750933.0,406156661.0,416807868.0,427820358.0,439173286.0,450928044.0,463076637.0,475606210.0,488580707.0,502070763.0,516003448.0,530308387.0,544737983.0,559609961.0,575202699.0,590968990.0,607123269.0,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,10266395.0,10505959.0,10756922.0,11017409.0,11290128.0,11567667.0,11853696.0,12157999.0,12469127.0,12773954.0,13059851.0,13340756.0,13611441.0,13655567.0,13169311.0,11937581.0,10991378.0,10917982.0,11190221.0,11426852.0,11420074.0,11387818.0,11523298.0,11874088.0,12045660.0,12238879.0,13278974.0,14943172.0,16250794.0,17065836.0,17763266.0,18452091.0,19159996.0,19887785.0,20130327.0,20284307.0,21378117.0,22733049.0,23560654.0,24404567.0,25424094.0,25909852.0,26482622.0,27466101.0,28284089.0,29347708.0,30560034.0,31622704.0,32792523.0,33831764.0,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,111246953.0,113795019.0,116444636.0,119203521.0,122086536.0,125072948.0,128176494.0,131449942.0,134911581.0,138569918.0,142337272.0,146258576.0,150402616.0,154721711.0,159166518.0,163762473.0,168585118.0,173255157.0,177880746.0,182811038.0,187889141.0,193104347.0,198485027.0,204062274.0,209566031.0,215178709.0,221191375.0,227246778.0,233360104.0,239801875.0,246415446.0,253207584.0,260297834.0,267506298.0,274968446.0,282780717.0,290841795.0,299142845.0,307725100.0,316588476.0,325663158.0,334984176.0,344586109.0,354343844.0,364358270.0,374790143.0,385360349.0,396030207.0,406992047.0,418127845.0,429454743.0,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,5581386.0,5641807.0,5702699.0,5763685.0,5852788.0,5991102.0,6174262.0,6388528.0,6613367.0,6842947.0,7074664.0,7317829.0,7576734.0,7847207.0,8133872.0,8435607.0,8751648.0,9082983.0,9425917.0,9779120.0,10139450.0,10497858.0,10861291.0,11238562.0,11626360.0,12023529.0,12423712.0,12827135.0,13249764.0,13699778.0,14170973.0,14660413.0,15159370.0,15667235.0,16194869.0,16747208.0,17327699.0,17943712.0,18600423.0,19291161.0,20015279.0,20778561.0,21578655.0,22414773.0,23294825.0,24218352.0,25177394.0,26165620.0,27160769.0,28157798.0,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN

In [14]:
# Electricity
print(f"Dimensions Electricity : {df_access.shape}")
df_pop.head(5)

Dimensions Electricity : (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,58694.0,58990.0,59069.0,59052.0,58950.0,58781.0,58047.0,58299.0,58349.0,58295.0,58368.0,58580.0,58776.0,59191.0,59909.0,60563.0,61276.0,62228.0,62901.0,61728.0,59931.0,59159.0,59331.0,60443.0,62753.0,65896.0,69005.0,73685.0,77595.0,79805.0,83021.0,86301.0,88451.0,89659.0,90588.0,91439.0,92074.0,93128.0,95138.0,97635.0,99405.0,100150.0,100917.0,101604.0,101838.0,102591.0,104110.0,105675.0,106807.0,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,153281203.0,157704381.0,162329396.0,167088245.0,171984985.0,177022314.0,182126556.0,187524135.0,193186642.0,198914573.0,204802976.0,210680842.0,217074286.0,223974122.0,230792729.0,238043099.0,245822010.0,253644643.0,261458202.0,269450407.0,277621771.0,286067346.0,294498625.0,302939121.0,311748681.0,320442961.0,329082707.0,338324002.0,347441809.0,356580375.0,366138524.0,375646235.0,385505757.0,395750933.0,406156661.0,416807868.0,427820358.0,439173286.0,450928044.0,463076637.0,475606210.0,488580707.0,502070763.0,516003448.0,530308387.0,544737983.0,559609961.0,575202699.0,590968990.0,607123269.0,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,10266395.0,10505959.0,10756922.0,11017409.0,11290128.0,11567667.0,11853696.0,12157999.0,12469127.0,12773954.0,13059851.0,13340756.0,13611441.0,13655567.0,13169311.0,11937581.0,10991378.0,10917982.0,11190221.0,11426852.0,11420074.0,11387818.0,11523298.0,11874088.0,12045660.0,12238879.0,13278974.0,14943172.0,16250794.0,17065836.0,17763266.0,18452091.0,19159996.0,19887785.0,20130327.0,20284307.0,21378117.0,22733049.0,23560654.0,24404567.0,25424094.0,25909852.0,26482622.0,27466101.0,28284089.0,29347708.0,30560034.0,31622704.0,32792523.0,33831764.0,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,111246953.0,113795019.0,116444636.0,119203521.0,122086536.0,125072948.0,128176494.0,131449942.0,134911581.0,138569918.0,142337272.0,146258576.0,150402616.0,154721711.0,159166518.0,163762473.0,168585118.0,173255157.0,177880746.0,182811038.0,187889141.0,193104347.0,198485027.0,204062274.0,209566031.0,215178709.0,221191375.0,227246778.0,233360104.0,239801875.0,246415446.0,253207584.0,260297834.0,267506298.0,274968446.0,282780717.0,290841795.0,299142845.0,307725100.0,316588476.0,325663158.0,334984176.0,344586109.0,354343844.0,364358270.0,374790143.0,385360349.0,396030207.0,406992047.0,418127845.0,429454743.0,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,5581386.0,5641807.0,5702699.0,5763685.0,5852788.0,5991102.0,6174262.0,6388528.0,6613367.0,6842947.0,7074664.0,7317829.0,7576734.0,7847207.0,8133872.0,8435607.0,8751648.0,9082983.0,9425917.0,9779120.0,10139450.0,10497858.0,10861291.0,11238562.0,11626360.0,12023529.0,12423712.0,12827135.0,13249764.0,13699778.0,14170973.0,14660413.0,15159370.0,15667235.0,16194869.0,16747208.0,17327699.0,17943712.0,18600423.0,19291161.0,20015279.0,20778561.0,21578655.0,22414773.0,23294825.0,24218352.0,25177394.0,26165620.0,27160769.0,28157798.0,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN

EDA - Valeurs Manquantes et Doublons

In [13]:
# Analyse des valeurs manquantes et doublons pour Energy Mix
print("Valeurs manquantes Energy Mix :\n", df_energy.isnull().sum())
print("\nDoublons Energy Mix :", df_energy.duplicated().sum())

Valeurs manquantes Energy Mix :
 Entity                 0
Code                1920
Year                   0
Oil                 1454
Gas                 1454
Coal                1454
Hydropower          1454
Solar               1454
Wind                1454
Nuclear                0
Other renewables    1454
dtype: int64

Doublons Energy Mix : 0

In [5]:
# Analyse des valeurs manquantes et doublons pour CO2
print("Valeurs manquantes CO2 :\n", df_co2.isnull().sum())
print("\nDoublons CO2 :", df_co2.duplicated().sum())

Valeurs manquantes CO2 :
 country                            0
year                               0
iso_code                        7931
population                      9244
gdp                            35160
                               ...
temperature_change_from_n2o    12131
total_ghg                      12261
total_ghg_excluding_lucf       12598
trade_co2                      45699
trade_co2_share                45699
Length: 79, dtype: int64

Doublons CO2 : 0

In [18]:
# Analyse des valeurs manquantes et doublons pour GDP (Aperçu des colonnes années)
print("Valeurs manquantes GDP (Colonnes de fin) :\n", df_gdp.isnull().sum().tail(10))
print("\nDoublons GDP :", df_gdp.duplicated().sum())

Valeurs manquantes GDP (Colonnes de fin) :
 2016             7
2017             7
2018             7
2019             7
2020             8
2021             8
2022             9
2023            15
2024            26
Unnamed: 69    266
dtype: int64

Doublons GDP : 0

In [4]:
# Analyse des valeurs manquantes et doublons pour Population
print("Valeurs manquantes Population (Colonnes de fin) :\n", df_pop.isnull().sum().tail(10))
print("\nDoublons Population :", df_pop.duplicated().sum())

Valeurs manquantes Population (Colonnes de fin) :
 2016             1
2017             1
2018             1
2019             1
2020             1
2021             1
2022             1
2023             1
2024             1
Unnamed: 69    266
dtype: int64

Doublons Population : 0

In [15]:
# Analyse des valeurs manquantes et doublons pour Access to Electricity
print("Valeurs manquantes Access Electricity (Colonnes de fin) :\n", df_access.isnull().sum().tail(10))
print("\nDoublons Access Electricity :", df_access.duplicated().sum())

Valeurs manquantes Access Electricity (Colonnes de fin) :
 2016             3
2017             3
2018             3
2019             3
2020             3
2021             3
2022             3
2023             3
2024           266
Unnamed: 69    266
dtype: int64

Doublons Access Electricity : 0

EDA - Description des Dataframes

In [18]:
print("Description de DataFrame Energy \n",df_energy.describe())

Description de DataFrame Energy
               Year           Oil           Gas          Coal   Hydropower  \
count  7859.000000   6405.000000   6405.000000   6405.000000  6405.000000
mean   1995.774017   2304.061156   1284.206388   1682.740233   143.118584
std      17.127688   6079.290689   3670.941634   5153.876464   396.191343
min    1965.000000      0.000000      0.000000      0.000000     0.000000
25%    1981.000000     80.388960     11.880710      4.348958     1.299700
50%    1996.000000    204.001390     82.808750     47.364048    10.376336
75%    2011.000000   1013.221800    440.570400    446.305180    58.248610
max    2024.000000  55292.082000  41278.270000  45850.543000  4452.908700

             Solar         Wind      Nuclear  Other renewables
count  6405.000000  6405.000000  7859.000000       6405.000000
mean      9.571080    19.510164    85.798703         13.616880
std      73.189415   114.220451   321.529369         51.155146
min       0.000000     0.000000     0.000000          0.000000
25%       0.000000     0.000000     0.000000          0.000000
50%       0.000000     0.000000     0.000000          0.177700
75%       0.036000     0.344870     9.558876          3.591849
max    2111.733400  2511.030800  2817.452400        792.434140

In [6]:
print("Description de DataFrame co2 \n",df_co2.describe())

Description de DataFrame co2
                year    population           gdp    cement_co2  \
count  50411.000000  4.116700e+04  1.525100e+04  29173.000000
mean    1920.349249  6.017453e+07  3.300495e+11      7.890109
std       65.859123  3.308433e+08  3.086383e+12     62.988171
min     1750.000000  2.150000e+02  4.998000e+07      0.000000
25%     1875.000000  3.272140e+05  7.874038e+09      0.000000
50%     1925.000000  2.291594e+06  2.743861e+10      0.000000
75%     1975.000000  9.986553e+06  1.212627e+11      0.524000
max     2024.000000  8.161973e+09  1.301126e+14   1666.885000

       cement_co2_per_capita           co2  co2_growth_abs  co2_growth_prct  \
count           25648.000000  29384.000000    27216.000000     26239.000000
mean                0.060013    420.227035        6.268847        42.598225
std                 0.123562   1972.092032       62.199548      1721.913018
min                 0.000000      0.000000    -1928.339000      -100.000000
25%                 0.000000      0.381000       -0.005000        -1.070500
50%                 0.001000      5.081000        0.044000         3.813000
75%                 0.076250     53.656500        1.018000        10.884000
max                 2.484000  38598.578000     1804.657000    180870.000000

       co2_including_luc  co2_including_luc_growth_abs  \
count       23796.000000                  23496.000000
mean          544.144592                      7.483698
std          2273.281696                     99.512520
min           -84.560000                  -2298.978000
25%             6.667750                     -0.727500
50%            28.120000                      0.112000
75%           124.303250                      2.765250
max         43184.086000                   2614.874000

       co2_including_luc_growth_prct  co2_including_luc_per_capita  \
count                   23496.000000                  23757.000000
mean                        4.132343                      7.115213
std                       166.964358                      8.921278
min                    -11927.241000                    -12.455000
25%                        -3.784500                      2.058000
50%                         1.183000                      4.536000
75%                         6.092000                      9.113000
max                      6362.499000                    364.809000

       co2_including_luc_per_gdp  co2_including_luc_per_unit_energy  \
count               16790.000000                        10020.00000
mean                    2.328426                            1.34943
std                     5.626872                            6.71123
min                   -12.938000                           -8.67400
25%                     0.398000                            0.20300
50%                     0.878000                            0.28300
75%                     2.151000                            0.81100
max                   291.293000                          511.46900

       co2_per_capita   co2_per_gdp  co2_per_unit_energy      coal_co2  \
count    26509.000000  17528.000000         10699.000000  21925.000000
mean         3.821369      0.397679             0.252187    185.496070
std         14.312866      0.754065             0.317041    855.418419
min          0.000000      0.000000             0.000000      0.000000
25%          0.171000      0.131750             0.188000      0.068000
50%          1.023000      0.264000             0.222000      2.096000
75%          4.327000      0.509000             0.262000     27.857000
max        782.743000     82.599000            10.689000  15805.254000

       coal_co2_per_capita  consumption_co2  consumption_co2_per_capita  \
count         21314.000000      5053.000000                 4643.000000
mean              1.285323      1318.129607                    6.463376
std               2.351090      3904.104954                    6.852514
min               0.000000         0.000000                    0.000000
25%               0.017000        12.079000                    1.127000
50%               0.227000        74.336000                    4.323000
75%               1.583000       454.813000                    9.791500
max              34.295000     38598.578000                   63.272000

       consumption_co2_per_gdp  cumulative_cement_co2  cumulative_co2  \
count              4448.000000           29151.000000    2.756300e+04
mean                  0.349924             196.486344    1.249223e+04
std                   0.247281            1495.918343    7.312143e+04
min                   0.000000               0.000000    0.000000e+00
25%                   0.208000               0.000000    4.238000e+00
50%                   0.301000               0.000000    8.046600e+01
75%                   0.428000               9.816500    1.163684e+03
max                   3.306000           49693.922000    1.849124e+06

       cumulative_co2_including_luc  cumulative_coal_co2  \
count                  2.379600e+04         21925.000000
mean                   2.790247e+04          9311.023979
std                    1.269563e+05         43499.981365
min                   -1.203450e+02             0.000000
25%                    1.836610e+02             1.549000
50%                    1.039956e+03            57.155000
75%                    5.151784e+03           915.739000
max                    2.751504e+06        849832.250000

       cumulative_flaring_co2  cumulative_gas_co2  cumulative_luc_co2  \
count            16111.000000        18147.000000        37450.000000
mean               177.231149         1876.820098         9998.375654
std                926.732659        11756.922691        46043.141427
min                  0.000000            0.000000        -3918.006000
25%                  0.000000            0.000000           12.678500
50%                  0.000000            0.189000          282.849500
75%                  6.169000           88.334000         1758.260000
max              20141.375000       276572.688000       906953.562000

       cumulative_oil_co2  cumulative_other_co2  energy_per_capita  \
count        25458.000000           3254.000000       10459.000000
mean          3777.605153            417.861562       24325.863595
std          24886.829185           1317.317547       32302.447508
min              0.000000              0.000000           0.000000
25%              0.909000              0.266000        2702.109500
50%             24.131000             21.406500       11883.904000
75%            312.618250            131.841500       35563.351500
max         638014.188000          14869.403000      318559.688000

       energy_per_gdp   flaring_co2  flaring_co2_per_capita       gas_co2  \
count     7787.000000  16174.000000            14910.000000  18147.000000
mean         1.671652      5.854644                0.270544     74.840369
std          1.630303     26.749898                2.995049    397.296985
min          0.000000      0.000000                0.000000      0.000000
25%          0.764000      0.000000                0.000000      0.000000
50%          1.244000      0.000000                0.000000      0.018000
75%          2.053000      0.337000                0.031000      6.606500
max         25.253000    432.392000              114.509000   8009.828000

       gas_co2_per_capita  ghg_excluding_lucf_per_capita  ghg_per_capita  \
count        17446.000000                   35842.000000    36179.000000
mean             0.797031                       3.079828        7.716630
std              2.805144                       7.785475       11.276869
min              0.000000                       0.022000      -28.852000
25%              0.000000                       0.281000        1.943000
50%              0.004000                       0.660000        4.278000
75%              0.453750                       2.832000        9.235000
max             53.476000                     369.650000      369.705000

       land_use_change_co2  land_use_change_co2_per_capita       methane  \
count         37450.000000                    36635.000000  38150.000000
mean            124.752927                        3.905389     95.277707
std             519.818810                        9.106628    434.707032
min            -319.418000                      -45.317000      0.000000
25%               0.024000                        0.121000      0.389000
50%               3.396500                        1.305000      3.462500
75%              23.189250                        4.258000     18.546750
max            8692.767000                      305.195000   9498.914000

       methane_per_capita  nitrous_oxide  nitrous_oxide_per_capita  \
count        36179.000000   38500.000000              36439.000000
mean             1.741395      25.424751                  0.444565
std              3.832717     129.896895                  0.799293
min              0.032000       0.000000                  0.000000
25%              0.614500       0.071000                  0.109000
50%              1.006000       0.706000                  0.224000
75%              1.692000       5.150000                  0.457000
max            133.104000    2935.779000                 20.393000

            oil_co2  oil_co2_per_capita  other_co2_per_capita  \
count  25459.000000        24722.000000           2659.000000
mean     115.307630            2.192688              0.082205
std      646.556645           13.948773              0.079726
min        0.000000            0.000000              0.000000
25%        0.088000            0.048000              0.023500
50%        1.398000            0.404000              0.065000
75%       14.412500            2.012750              0.115000
max    12470.596000          782.743000              0.604000

       other_industry_co2  primary_energy_consumption  \
count         3254.000000                10503.000000
mean            20.116569                 2480.146340
std             55.644708                11449.335316
min              0.000000                    0.000000
25%              0.013000                    6.822500
50%              1.321500                   59.671000
75%              6.403000                  465.178500
max            458.178000               176737.094000

       share_global_cement_co2  share_global_co2  \
count             22270.000000      27563.000000
mean                  3.002813          5.369860
std                  13.389959         18.734892
min                   0.000000          0.000000
25%                   0.000000          0.004000
50%                   0.026500          0.053000
75%                   0.365750          0.575000
max                 100.000000        100.000000

       share_global_co2_including_luc  share_global_coal_co2  \
count                    23796.000000           21925.000000
mean                         3.457512               6.791725
std                         11.709725              20.969463
min                         -0.375000               0.000000
25%                          0.041000               0.002000
50%                          0.176000               0.058000
75%                          0.838000               0.919000
max                        100.000000             100.000000

       share_global_cumulative_cement_co2  share_global_cumulative_co2  \
count                        22270.000000                 27563.000000
mean                             2.995657                     5.500642
std                             13.459332                    19.503609
min                              0.000000                     0.000000
25%                              0.000000                     0.002000
50%                              0.021000                     0.029000
75%                              0.345750                     0.401500
max                            100.000000                   100.000000

       share_global_cumulative_co2_including_luc  \
count                               23796.000000
mean                                    3.321957
std                                    11.675183
min                                    -0.101000
25%                                     0.027000
50%                                     0.144000
75%                                     0.688000
max                                   100.000000

       share_global_cumulative_coal_co2  share_global_cumulative_flaring_co2  \
count                      21925.000000                         11089.000000
mean                           6.974350                             3.043673
std                           21.797169                            11.239887
min                            0.000000                             0.000000
25%                            0.002000                             0.000000
50%                            0.040000                             0.004000
75%                            0.672000                             0.479000
max                          100.000000                           100.000000

       share_global_cumulative_gas_co2  share_global_cumulative_luc_co2  \
count                     15167.000000                     37450.000000
mean                          4.104541                         2.559362
std                          17.155976                         9.773304
min                           0.000000                        -0.518000
25%                           0.000000                         0.008000
50%                           0.014000                         0.105000
75%                           0.322000                         0.509000
max                         100.000000                       100.000000

       share_global_cumulative_oil_co2  share_global_cumulative_other_co2  \
count                     23833.000000                        2170.000000
mean                          3.351795                           7.053671
std                          13.260472                          17.554077
min                           0.000000                           0.000000
25%                           0.004000                           0.127000
50%                           0.057000                           0.431500
75%                           0.509000                           2.142250
max                         100.000000                         100.000000

       share_global_flaring_co2  share_global_gas_co2  share_global_luc_co2  \
count              11089.000000          15167.000000          37450.000000
mean                   3.126383              4.195698              2.439717
std                   11.147780             16.683568              9.800818
min                    0.000000              0.000000             -6.966000
25%                    0.000000              0.000000              0.001000
50%                    0.001000              0.026000              0.072000
75%                    0.669000              0.500500              0.486000
max                  100.000000            100.000000            100.000000

       share_global_oil_co2  share_global_other_co2  \
count          23833.000000             2170.000000
mean               3.333339                7.190616
std               13.031193               17.448980
min                0.000000                0.000000
25%                0.006000                0.144000
50%                0.067000                0.588500
75%                0.544000                2.416500
max              100.000000              100.000000

       share_of_temperature_change_from_ghg  temperature_change_from_ch4  \
count                          41238.000000                 38280.000000
mean                               2.272236                     0.002871
std                                9.282343                     0.015362
min                               -0.824000                    -0.001000
25%                                0.003000                     0.000000
50%                                0.081000                     0.000000
75%                                0.373000                     0.000000
max                              100.000000                     0.377000

       temperature_change_from_co2  temperature_change_from_ghg  \
count                 41238.000000                 41238.000000
mean                      0.008014                     0.011224
std                       0.045687                     0.062888
min                       0.000000                    -0.001000
25%                       0.000000                     0.000000
50%                       0.000000                     0.000000
75%                       0.001000                     0.002000
max                       1.216000                     1.678000

       temperature_change_from_n2o     total_ghg  total_ghg_excluding_lucf  \
count                 38280.000000  38150.000000              37813.000000
mean                      0.000509    490.799608                310.521459
std                       0.003048   2414.076755               1812.363570
min                       0.000000    -19.725000                  0.000000
25%                       0.000000      1.502000                  0.221000
50%                       0.000000     14.605500                  2.222000
75%                       0.000000     76.508500                 27.863000
max                       0.085000  54433.398000              43714.777000

         trade_co2  trade_co2_share
count  4712.000000      4712.000000
mean     -6.986781        21.468641
std     259.018184        62.637598
min   -2177.807000       -98.281000
25%      -2.262250        -6.828750
50%       1.641000         8.381500
75%      11.425500        32.782250
max    1768.846000      1023.042000

In [19]:
print("Description du DataFrame GDP \n", df_gdp.describe())

Description du DataFrame GDP
                1960          1961          1962          1963          1964  \
count  1.510000e+02  1.540000e+02  1.560000e+02  1.560000e+02  1.560000e+02
mean   6.738309e+10  6.967855e+10  7.320963e+10  7.951608e+10  8.731648e+10
std    2.013541e+11  2.114096e+11  2.259814e+11  2.435522e+11  2.666902e+11
min    1.201202e+07  1.159202e+07  1.254164e+07  1.283330e+07  1.341663e+07
25%    5.079241e+08  5.104649e+08  5.636808e+08  5.780962e+08  5.876399e+08
50%    3.359404e+09  3.330233e+09  3.296617e+09  3.802982e+09  3.956737e+09
75%    3.311980e+10  3.307499e+10  3.295975e+10  3.764277e+10  3.803517e+10
max    1.366488e+12  1.443969e+12  1.544903e+12  1.670355e+12  1.831030e+12

               1965          1966          1967          1968          1969  \
count  1.620000e+02  1.630000e+02  1.670000e+02  1.680000e+02  1.680000e+02
mean   9.184715e+10  9.847902e+10  1.015524e+11  1.087340e+11  1.204076e+11
std    2.854069e+11  3.098385e+11  3.258925e+11  3.516865e+11  3.877120e+11
min    1.359393e+07  1.446908e+07  1.583511e+07  1.460000e+07  1.585000e+07
25%    6.009141e+08  6.593318e+08  6.548745e+08  6.211906e+08  6.806268e+08
50%    3.479179e+09  3.957065e+09  3.532700e+09  4.537000e+09  5.087251e+09
75%    3.642291e+10  3.878473e+10  3.787713e+10  4.178077e+10  4.670788e+10
max    1.995235e+12  2.162708e+12  2.294873e+12  2.479815e+12  2.739124e+12

               1970          1971          1972          1973          1974  \
count  1.900000e+02  1.910000e+02  1.910000e+02  1.910000e+02  1.910000e+02
mean   1.170634e+11  1.283824e+11  1.481328e+11  1.829776e+11  2.143485e+11
std    4.014830e+11  4.433385e+11  5.129450e+11  6.242564e+11  7.103726e+11
min    2.585956e+06  2.716990e+06  2.968458e+06  3.411915e+06  4.122329e+06
25%    3.590548e+08  3.999335e+08  4.803306e+08  5.746309e+08  7.105137e+08
50%    3.250772e+09  3.865347e+09  4.203069e+09  5.152080e+09  7.684800e+09
75%    4.128733e+10  4.593498e+10  5.345253e+10  6.591281e+10  8.822902e+10
max    3.004258e+12  3.319897e+12  3.834214e+12  4.688558e+12  5.419514e+12

               1975          1976          1977          1978          1979  \
count  1.950000e+02  1.950000e+02  1.980000e+02  1.970000e+02  1.980000e+02
mean   2.342462e+11  2.535972e+11  2.821229e+11  3.331349e+11  3.853139e+11
std    7.865111e+11  8.527181e+11  9.566124e+11  1.142622e+12  1.319273e+12
min    4.014748e+06  3.919072e+06  3.669420e+06  3.798782e+06  4.065659e+06
25%    8.236814e+08  8.730129e+08  8.354473e+08  1.000555e+09  1.201530e+09
50%    7.731674e+09  8.968600e+09  8.691874e+09  1.116500e+10  1.133984e+10
75%    9.446541e+10  9.261947e+10  9.478933e+10  1.117339e+11  1.317008e+11
max    6.035142e+12  6.560174e+12  7.416443e+12  8.779662e+12  1.015546e+13

               1980          1981          1982          1983          1984  \
count  2.080000e+02  2.080000e+02  2.090000e+02  2.090000e+02  2.110000e+02
mean   4.172229e+11  4.323123e+11  4.240556e+11  4.270167e+11  4.360302e+11
std    1.443698e+12  1.471789e+12  1.453604e+12  1.492039e+12  1.547505e+12
min    4.206128e+06  4.773018e+06  4.118945e+06  4.152550e+06  4.481978e+06
25%    1.304003e+09  1.279217e+09  1.267779e+09  1.236017e+09  1.304212e+09
50%    1.083589e+10  1.151288e+10  1.192603e+10  1.100671e+10  1.044762e+10
75%    1.372550e+11  1.661175e+11  1.532403e+11  1.514214e+11  1.360174e+11
max    1.145277e+13  1.184344e+13  1.171928e+13  1.196297e+13  1.242796e+13

               1985          1986          1987          1988          1989  \
count  2.130000e+02  2.130000e+02  2.200000e+02  2.230000e+02  2.230000e+02
mean   4.512664e+11  5.256708e+11  5.769878e+11  6.386476e+11  6.666748e+11
std    1.618061e+12  1.935797e+12  2.191464e+12  2.439596e+12  2.546374e+12
min    3.862852e+06  4.574706e+06  5.020513e+06  7.011059e+06  8.454523e+06
25%    1.362072e+09  1.532105e+09  1.820306e+09  2.048861e+09  2.155996e+09
50%    9.721652e+09  1.009220e+10  9.892185e+09  1.057704e+10  1.010185e+10
75%    1.380051e+11  1.345560e+11  1.436207e+11  1.719551e+11  1.799649e+11
max    1.301698e+13  1.534844e+13  1.747224e+13  1.952482e+13  2.039581e+13

               1990          1991          1992          1993          1994  \
count  2.400000e+02  2.410000e+02  2.420000e+02  2.430000e+02  2.440000e+02
mean   7.061620e+11  7.269942e+11  7.713532e+11  7.800925e+11  8.372811e+11
std    2.771145e+12  2.902830e+12  3.105885e+12  3.131528e+12  3.352158e+12
min    9.542901e+06  1.012731e+07  1.053503e+07  1.041440e+07  1.177261e+07
25%    2.549471e+09  2.529727e+09  2.316321e+09  2.168950e+09  1.927366e+09
50%    1.239671e+10  1.120618e+10  1.095389e+10  1.140002e+10  1.225570e+10
75%    1.694605e+11  1.800134e+11  1.653224e+11  1.778302e+11  1.802971e+11
max    2.292275e+13  2.392090e+13  2.554696e+13  2.597492e+13  2.796145e+13

               1995          1996          1997          1998          1999  \
count  2.470000e+02  2.470000e+02  2.490000e+02  2.500000e+02  2.500000e+02
mean   9.303983e+11  9.603445e+11  9.522640e+11  9.450225e+11  9.631101e+11
std    3.711414e+12  3.768061e+12  3.712163e+12  3.709352e+12  3.858365e+12
min    1.192261e+07  1.333860e+07  1.373421e+07  1.379515e+07  1.480050e+07
25%    2.398425e+09  2.740718e+09  2.450351e+09  2.807948e+09  2.975305e+09
50%    1.302970e+10  1.378956e+10  1.450523e+10  1.511595e+10  1.498340e+10
75%    2.106156e+11  2.316611e+11  2.157490e+11  2.180792e+11  1.914023e+11
max    3.124542e+13  3.196895e+13  3.187056e+13  3.173375e+13  3.278283e+13

               2000          2001          2002          2003          2004  \
count  2.520000e+02  2.530000e+02  2.570000e+02  2.570000e+02  2.570000e+02
mean   9.876677e+11  9.806802e+11  1.003941e+12  1.132683e+12  1.286312e+12
std    3.942763e+12  3.912867e+12  4.047214e+12  4.542637e+12  5.092003e+12
min    1.507398e+07  1.396473e+07  1.684267e+07  1.945634e+07  2.279827e+07
25%    3.058994e+09  2.813572e+09  3.034251e+09  3.503723e+09  4.043551e+09
50%    1.438707e+10  1.418345e+10  1.459490e+10  1.782544e+10  2.066253e+10
75%    1.911816e+11  1.918232e+11  1.956606e+11  2.185612e+11  2.579393e+11
max    3.389816e+13  3.369042e+13  3.499153e+13  3.924328e+13  4.422538e+13

               2005          2006          2007          2008          2009  \
count  2.570000e+02  2.580000e+02  2.580000e+02  2.590000e+02  2.610000e+02
mean   1.407700e+12  1.538586e+12  1.761370e+12  1.957510e+12  1.847584e+12
std    5.453510e+12  5.841831e+12  6.529468e+12  7.099069e+12  6.683731e+12
min    2.290998e+07  2.409688e+07  2.276697e+07  3.187443e+07  2.807698e+07
25%    4.865893e+09  5.107132e+09  5.830723e+09  6.600506e+09  6.037140e+09
50%    2.149734e+10  2.399848e+10  3.068935e+10  3.413520e+10  3.539958e+10
75%    3.099786e+11  3.466608e+11  4.130665e+11  4.959263e+11  4.290979e+11
max    4.790049e+13  5.192351e+13  5.852579e+13  6.431173e+13  6.098226e+13

               2010          2011          2012          2013          2014  \
count  2.610000e+02  2.620000e+02  2.600000e+02  2.600000e+02  2.610000e+02
mean   2.050193e+12  2.294288e+12  2.371716e+12  2.455097e+12  2.515760e+12
std    7.237831e+12  8.002372e+12  8.182074e+12  8.415416e+12  8.622683e+12
min    3.210541e+07  3.919696e+07  3.934558e+07  3.861589e+07  3.876098e+07
25%    6.853467e+09  7.101249e+09  8.585723e+09  8.518532e+09  9.112605e+09
50%    4.067658e+10  4.502799e+10  4.456003e+10  4.957049e+10  5.142710e+10
75%    4.815565e+11  5.295807e+11  5.469217e+11  5.325171e+11  5.421342e+11
max    6.681119e+13  7.430971e+13  7.596059e+13  7.803489e+13  8.005489e+13

               2015          2016          2017          2018          2019  \
count  2.600000e+02  2.590000e+02  2.590000e+02  2.590000e+02  2.590000e+02
mean   2.380880e+12  2.422449e+12  2.595069e+12  2.763906e+12  2.815728e+12
std    8.180010e+12  8.332461e+12  8.867716e+12  9.447837e+12  9.599437e+12
min    3.681194e+07  4.162906e+07  4.527660e+07  4.801526e+07  5.412320e+07
25%    8.780202e+09  8.645614e+09  9.213441e+09  9.961398e+09  1.019058e+10
50%    4.968307e+10  4.977441e+10  5.327488e+10  5.852248e+10  6.102673e+10
75%    4.951706e+11  4.958382e+11  5.317645e+11  5.461441e+11  5.733302e+11
max    7.562191e+13  7.683168e+13  8.183910e+13  8.705096e+13  8.848326e+13

               2020          2021          2022          2023          2024  \
count  2.580000e+02  2.580000e+02  2.570000e+02  2.510000e+02  2.400000e+02
mean   2.740336e+12  3.149174e+12  3.295601e+12  3.516846e+12  3.820289e+12
std    9.370977e+12  1.071027e+13  1.113559e+13  1.177089e+13  1.249838e+13
min    5.174659e+07  6.019641e+07  5.906598e+07  6.228031e+07  1.625886e+08
25%    9.564426e+09  1.032321e+10  1.242906e+10  1.471340e+10  1.730330e+10
50%    5.471669e+10  6.211398e+10  7.059411e+10  7.978988e+10  9.313183e+10
75%    5.850065e+11  6.260569e+11  6.469503e+11  8.534380e+11  1.124337e+12
max    8.591276e+13  9.814048e+13  1.022515e+14  1.067416e+14  1.109827e+14

       Unnamed: 69
count          0.0
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN

In [5]:
print("Description du DataFrame Population \n", df_pop.describe())

Description du DataFrame Population
                1960          1961          1962          1963          1964  \
count  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02
mean   1.153986e+08  1.170032e+08  1.191639e+08  1.218340e+08  1.245281e+08
std    3.616512e+08  3.661333e+08  3.727667e+08  3.813673e+08  3.900147e+08
min    2.715000e+03  2.970000e+03  3.264000e+03  3.584000e+03  3.922000e+03
25%    5.152028e+05  5.255230e+05  5.363018e+05  5.475875e+05  5.593638e+05
50%    3.659633e+06  3.747132e+06  3.831900e+06  3.919710e+06  4.010150e+06
75%    2.686293e+07  2.761326e+07  2.837302e+07  2.915448e+07  2.995223e+07
max    3.021513e+09  3.062768e+09  3.117372e+09  3.184063e+09  3.251253e+09

               1965          1966          1967          1968          1969  \
count  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02
mean   1.272539e+08  1.300993e+08  1.329525e+08  1.358805e+08  1.389068e+08
std    3.987681e+08  4.079973e+08  4.172128e+08  4.266920e+08  4.365296e+08
min    4.282000e+03  4.664000e+03  5.071000e+03  5.500000e+03  5.631000e+03
25%    5.675750e+05  5.711695e+05  5.779525e+05  5.825170e+05  5.861185e+05
50%    4.102976e+06  4.198738e+06  4.297792e+06  4.396290e+06  4.503420e+06
75%    3.075921e+07  3.147516e+07  3.203946e+07  3.247057e+07  3.277149e+07
max    3.318998e+09  3.389087e+09  3.459015e+09  3.530704e+09  3.604816e+09

               1970          1971          1972          1973          1974  \
count  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02
mean   1.419965e+08  1.451506e+08  1.482476e+08  1.513910e+08  1.545260e+08
std    4.466126e+08  4.568952e+08  4.669377e+08  4.770679e+08  4.871094e+08
min    5.663000e+03  5.685000e+03  5.692000e+03  5.681000e+03  5.822000e+03
25%    5.944680e+05  6.063812e+05  6.220452e+05  6.478048e+05  6.593632e+05
50%    4.564116e+06  4.606994e+06  4.696757e+06  4.833704e+06  4.957996e+06
75%    3.295186e+07  3.321815e+07  3.378017e+07  3.432460e+07  3.486253e+07
max    3.680589e+09  3.758614e+09  3.834446e+09  3.911068e+09  3.987294e+09

               1975          1976          1977          1978          1979  \
count  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02
mean   1.576057e+08  1.606489e+08  1.636745e+08  1.667643e+08  1.699479e+08
std    4.969070e+08  5.065405e+08  5.160747e+08  5.257506e+08  5.356863e+08
min    6.117000e+03  6.404000e+03  6.686000e+03  6.957000e+03  7.184000e+03
25%    6.614990e+05  6.900502e+05  7.338940e+05  7.849170e+05  8.074158e+05
50%    5.053319e+06  5.162123e+06  5.300978e+06  5.392241e+06  5.548640e+06
75%    3.540002e+07  3.592085e+07  3.643676e+07  3.700852e+07  3.775692e+07
max    4.062071e+09  4.135759e+09  4.208959e+09  4.283431e+09  4.360056e+09

               1980          1981          1982          1983          1984  \
count  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02
mean   1.731726e+08  1.764617e+08  1.799025e+08  1.833943e+08  1.868812e+08
std    5.458042e+08  5.562021e+08  5.671189e+08  5.781601e+08  5.891620e+08
min    7.366000e+03  7.526000e+03  7.664000e+03  7.789000e+03  7.902000e+03
25%    8.155690e+05  8.259372e+05  8.392398e+05  8.549452e+05  8.710145e+05
50%    5.743968e+06  5.878281e+06  6.005477e+06  6.148154e+06  6.285454e+06
75%    3.855341e+07  3.953976e+07  4.056280e+07  4.144019e+07  4.225297e+07
max    4.437603e+09  4.516926e+09  4.599539e+09  4.682925e+09  4.766040e+09

               1985          1986          1987          1988          1989  \
count  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02
mean   1.904372e+08  1.940873e+08  1.978347e+08  2.016118e+08  2.053996e+08
std    6.003858e+08  6.119426e+08  6.238345e+08  6.358261e+08  6.478028e+08
min    8.046000e+03  8.217000e+03  8.371000e+03  8.518000e+03  8.662000e+03
25%    8.879912e+05  9.075992e+05  9.300338e+05  9.631352e+05  9.979650e+05
50%    6.423294e+06  6.542180e+06  6.702338e+06  6.845621e+06  7.037884e+06
75%    4.299988e+07  4.370471e+07  4.472396e+07  4.604433e+07  4.738922e+07
max    4.850741e+09  4.937712e+09  5.027030e+09  5.117167e+09  5.207655e+09

               1990          1991          1992          1993          1994  \
count  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02
mean   2.084487e+08  2.121585e+08  2.158512e+08  2.195401e+08  2.231764e+08
std    6.587567e+08  6.704482e+08  6.819258e+08  6.932737e+08  7.044588e+08
min    8.798000e+03  8.928000e+03  9.038000e+03  9.126000e+03  9.207000e+03
25%    1.054696e+06  1.070266e+06  1.084441e+06  1.097374e+06  1.112846e+06
50%    7.130142e+06  7.271300e+06  7.382050e+06  7.494800e+06  7.419771e+06
75%    4.760976e+07  4.971720e+07  5.185375e+07  5.235013e+07  5.207600e+07
max    5.299247e+09  5.388496e+09  5.477124e+09  5.564779e+09  5.650853e+09

               1995          1996          1997          1998          1999  \
count  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02
mean   2.267973e+08  2.304315e+08  2.340588e+08  2.376874e+08  2.412759e+08
std    7.156141e+08  7.268254e+08  7.380214e+08  7.491718e+08  7.601290e+08
min    9.280000e+03  9.342000e+03  9.400000e+03  9.451000e+03  9.496000e+03
25%    1.123213e+06  1.152015e+06  1.181439e+06  1.211736e+06  1.243016e+06
50%    7.562546e+06  7.707557e+06  7.838250e+06  8.002143e+06  8.151296e+06
75%    5.166554e+07  5.122611e+07  5.078688e+07  5.037973e+07  4.997645e+07
max    5.736506e+09  5.822615e+09  5.908467e+09  5.994040e+09  6.078404e+09

               2000          2001          2002          2003          2004  \
count  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02
mean   2.448235e+08  2.483665e+08  2.518967e+08  2.554309e+08  2.589965e+08
std    7.709322e+08  7.816644e+08  7.922168e+08  8.026984e+08  8.132663e+08
min    9.544000e+03  9.586000e+03  9.623000e+03  9.695000e+03  9.816000e+03
25%    1.275572e+06  1.309589e+06  1.332011e+06  1.338709e+06  1.349563e+06
50%    8.213931e+06  8.287094e+06  8.400180e+06  8.586875e+06  8.816844e+06
75%    5.050744e+07  5.213265e+07  5.375052e+07  5.534387e+07  5.699774e+07
max    6.161885e+09  6.245113e+09  6.327557e+09  6.409750e+09  6.492770e+09

               2005          2006          2007          2008          2009  \
count  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02
mean   2.625745e+08  2.661923e+08  2.698134e+08  2.735083e+08  2.772370e+08
std    8.238232e+08  8.344275e+08  8.449883e+08  8.557224e+08  8.665611e+08
min    9.940000e+03  1.003400e+04  1.002000e+04  1.000900e+04  1.001600e+04
25%    1.354775e+06  1.346810e+06  1.340680e+06  1.426938e+06  1.526377e+06
50%    9.029572e+06  9.080505e+06  9.148092e+06  9.228466e+06  9.504583e+06
75%    5.816668e+07  5.839986e+07  5.875625e+07  5.921118e+07  5.955545e+07
max    6.575842e+09  6.659977e+09  6.744489e+09  6.830514e+09  6.916589e+09

               2010          2011          2012          2013          2014  \
count  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02
mean   2.809499e+08  2.847100e+08  2.886162e+08  2.924988e+08  2.963663e+08
std    8.774093e+08  8.884486e+08  8.999102e+08  9.113040e+08  9.226101e+08
min    1.004300e+04  1.009800e+04  1.026700e+04  1.051700e+04  1.074200e+04
25%    1.566347e+06  1.608076e+06  1.651417e+06  1.695973e+06  1.741122e+06
50%    9.745953e+06  9.914904e+06  1.006977e+07  1.019383e+07  1.031553e+07
75%    5.981941e+07  6.002684e+07  6.019125e+07  6.031161e+07  6.032071e+07
max    7.001267e+09  7.087120e+09  7.176929e+09  7.265892e+09  7.354068e+09

               2015          2016          2017          2018          2019  \
count  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02
mean   3.001948e+08  3.040206e+08  3.078413e+08  3.115874e+08  3.152613e+08
std    9.336943e+08  9.447157e+08  9.557272e+08  9.664012e+08  9.767615e+08
min    1.095400e+04  1.093000e+04  1.086900e+04  1.075100e+04  1.058100e+04
25%    1.786457e+06  1.777568e+06  1.791019e+06  1.797086e+06  1.788891e+06
50%    1.035808e+07  1.032545e+07  1.025915e+07  1.028382e+07  1.042338e+07
75%    6.022960e+07  6.011522e+07  6.000225e+07  6.014866e+07  5.972908e+07
max    7.441677e+09  7.528880e+09  7.614523e+09  7.697234e+09  7.778009e+09

               2020          2021          2022          2023          2024  \
count  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02  2.650000e+02
mean   3.187768e+08  3.219350e+08  3.250893e+08  3.283978e+08  3.318713e+08
std    9.865558e+08  9.952478e+08  1.003664e+09  1.012445e+09  1.021698e+09
min    1.039900e+04  1.019400e+04  9.992000e+03  9.816000e+03  9.646000e+03
25%    1.790151e+06  1.786079e+06  1.803545e+06  1.827816e+06  1.824359e+06
50%    1.069786e+07  1.050577e+07  1.048694e+07  1.064485e+07  1.090503e+07
75%    6.097280e+07  6.283041e+07  6.471182e+07  6.661761e+07  6.855165e+07
max    7.854748e+09  7.920515e+09  7.989545e+09  8.064058e+09  8.141809e+09

       Unnamed: 69
count          0.0
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN

In [16]:
print("Description du DataFrame Electricity \n", df_access.describe())

Description du DataFrame Electricity
        1960  1961  1962  1963  1964  1965  1966  1967  1968  1969  1970  1971  \
count   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
mean    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
std     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
min     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
25%     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
50%     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
75%     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
max     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

       1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  \
count   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
mean    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
std     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
min     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
25%     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
50%     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
75%     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
max     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

       1984  1985  1986  1987  1988  1989        1990        1991        1992  \
count   0.0   0.0   0.0   0.0   0.0   0.0  107.000000  118.000000  135.000000
mean    NaN   NaN   NaN   NaN   NaN   NaN   96.603436   92.224824   87.976218
std     NaN   NaN   NaN   NaN   NaN   NaN   13.176302   20.623349   25.752839
min     NaN   NaN   NaN   NaN   NaN   NaN   13.900000    5.600000    2.300000
25%     NaN   NaN   NaN   NaN   NaN   NaN   99.983841   99.703025   92.987717
50%     NaN   NaN   NaN   NaN   NaN   NaN  100.000000  100.000000  100.000000
75%     NaN   NaN   NaN   NaN   NaN   NaN  100.000000  100.000000  100.000000
max     NaN   NaN   NaN   NaN   NaN   NaN  100.000000  100.000000  100.000000

             1993        1994        1995        1996        1997        1998  \
count  149.000000  155.000000  162.000000  174.000000  182.000000  191.000000
mean    83.855243   82.802294   81.958601   79.425662   78.394713   77.491978
std     28.381584   29.247960   29.549384   31.077006   32.079725   32.079296
min      1.553556    0.533899    2.471727    2.811104    1.027836    2.174128
25%     78.836296   76.548321   73.599527   66.925000   65.428673   59.857632
50%    100.000000  100.000000  100.000000   99.952622   99.401811   98.657852
75%    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
max    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000

             1999        2000        2001        2002        2003        2004  \
count  199.000000  259.000000  259.000000  260.000000  260.000000  260.000000
mean    77.548445   74.450610   75.005290   75.261596   75.939510   76.384024
std     31.843361   32.483980   32.208768   31.969359   31.305193   30.922974
min      2.070949    2.100000    1.300000    1.300000    2.600000    3.500000
25%     59.084971   54.093759   53.800000   51.475000   53.350000   54.400000
50%     97.395111   93.400000   94.000000   94.400000   94.200000   94.378160
75%    100.000000  100.000000   99.996988  100.000000   99.923103   99.900000
max    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000

             2005        2006        2007        2008        2009        2010  \
count  260.000000  260.000000  262.000000  262.000000  263.000000  263.000000
mean    76.868883   77.809542   77.641235   78.308002   78.459139   79.327164
std     30.611660   30.048760   30.068939   29.781777   29.717065   29.224057
min      3.200000    2.700000    0.800000    1.300000    1.900000    1.500000
25%     58.475000   59.025000   57.400000   60.500000   60.600000   64.077374
50%     94.800000   96.250000   95.350000   96.350000   96.500000   96.800000
75%     99.829816   99.900000   99.997435  100.000000  100.000000  100.000000
max    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000

             2011        2012        2013        2014        2015        2016  \
count  263.000000  263.000000  263.000000  263.000000  263.000000  263.000000
mean    80.123723   80.824036   81.423948   82.145321   82.710609   83.819459
std     28.387341   27.801400   27.511239   26.969651   26.450707   25.496742
min      2.800000    3.300000    3.800000    4.300000    4.800000    5.300000
25%     66.200000   67.776714   69.400000   71.500000   73.400000   76.150000
50%     96.900000   97.200000   98.000000   98.100000   98.600000   99.034494
75%    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
max    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000

             2017        2018        2019        2020        2021        2022  \
count  263.000000  263.000000  263.000000  263.000000  263.000000  263.000000
mean    84.566219   85.202457   85.759857   86.293403   86.855188   87.147819
std     24.937006   24.083577   23.831564   23.429734   22.889985   22.500491
min      4.200000    6.300000    6.800000    7.300000    7.700000    8.400000
25%     79.350000   80.850000   83.750000   85.800000   85.985409   85.546194
50%     99.272112   99.600000   99.600000   99.700000   99.976387  100.000000
75%    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
max    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000

             2023  2024  Unnamed: 69
count  263.000000   0.0          0.0
mean    87.827610   NaN          NaN
std     21.788237   NaN          NaN
min      5.400000   NaN          NaN
25%     88.000000   NaN          NaN
50%    100.000000   NaN          NaN
75%    100.000000   NaN          NaN
max    100.000000   NaN          NaN

EDA - les infos des DataFrames

In [23]:
print("Info sur DataFrame Energy \n", df_energy.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7859 entries, 0 to 7858
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Entity            7859 non-null   object
 1   Code              5939 non-null   object
 2   Year              7859 non-null   int64
 3   Oil               6405 non-null   float64
 4   Gas               6405 non-null   float64
 5   Coal              6405 non-null   float64
 6   Hydropower        6405 non-null   float64
 7   Solar             6405 non-null   float64
 8   Wind              6405 non-null   float64
 9   Nuclear           7859 non-null   float64
 10  Other renewables  6405 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 675.5+ KB
Info sur DataFrame Energy
 None

In [7]:
print("Info sur DataFrame co2 \n", df_co2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50411 entries, 0 to 50410
Data columns (total 79 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    50411 non-null  object
 1   year                                       50411 non-null  int64
 2   iso_code                                   42480 non-null  object
 3   population                                 41167 non-null  float64
 4   gdp                                        15251 non-null  float64
 5   cement_co2                                 29173 non-null  float64
 6   cement_co2_per_capita                      25648 non-null  float64
 7   co2                                        29384 non-null  float64
 8   co2_growth_abs                             27216 non-null  float64
 9   co2_growth_prct                            26239 non-null  float64
 10  co2_including_luc                          23796 non-null  float64
 11  co2_including_luc_growth_abs               23496 non-null  float64
 12  co2_including_luc_growth_prct              23496 non-null  float64
 13  co2_including_luc_per_capita               23757 non-null  float64
 14  co2_including_luc_per_gdp                  16790 non-null  float64
 15  co2_including_luc_per_unit_energy          10020 non-null  float64
 16  co2_per_capita                             26509 non-null  float64
 17  co2_per_gdp                                17528 non-null  float64
 18  co2_per_unit_energy                        10699 non-null  float64
 19  coal_co2                                   21925 non-null  float64
 20  coal_co2_per_capita                        21314 non-null  float64
 21  consumption_co2                            5053 non-null   float64
 22  consumption_co2_per_capita                 4643 non-null   float64
 23  consumption_co2_per_gdp                    4448 non-null   float64
 24  cumulative_cement_co2                      29151 non-null  float64
 25  cumulative_co2                             27563 non-null  float64
 26  cumulative_co2_including_luc               23796 non-null  float64
 27  cumulative_coal_co2                        21925 non-null  float64
 28  cumulative_flaring_co2                     16111 non-null  float64
 29  cumulative_gas_co2                         18147 non-null  float64
 30  cumulative_luc_co2                         37450 non-null  float64
 31  cumulative_oil_co2                         25458 non-null  float64
 32  cumulative_other_co2                       3254 non-null   float64
 33  energy_per_capita                          10459 non-null  float64
 34  energy_per_gdp                             7787 non-null   float64
 35  flaring_co2                                16174 non-null  float64
 36  flaring_co2_per_capita                     14910 non-null  float64
 37  gas_co2                                    18147 non-null  float64
 38  gas_co2_per_capita                         17446 non-null  float64
 39  ghg_excluding_lucf_per_capita              35842 non-null  float64
 40  ghg_per_capita                             36179 non-null  float64
 41  land_use_change_co2                        37450 non-null  float64
 42  land_use_change_co2_per_capita             36635 non-null  float64
 43  methane                                    38150 non-null  float64
 44  methane_per_capita                         36179 non-null  float64
 45  nitrous_oxide                              38500 non-null  float64
 46  nitrous_oxide_per_capita                   36439 non-null  float64
 47  oil_co2                                    25459 non-null  float64
 48  oil_co2_per_capita                         24722 non-null  float64
 49  other_co2_per_capita                       2659 non-null   float64
 50  other_industry_co2                         3254 non-null   float64
 51  primary_energy_consumption                 10503 non-null  float64
 52  share_global_cement_co2                    22270 non-null  float64
 53  share_global_co2                           27563 non-null  float64
 54  share_global_co2_including_luc             23796 non-null  float64
 55  share_global_coal_co2                      21925 non-null  float64
 56  share_global_cumulative_cement_co2         22270 non-null  float64
 57  share_global_cumulative_co2                27563 non-null  float64
 58  share_global_cumulative_co2_including_luc  23796 non-null  float64
 59  share_global_cumulative_coal_co2           21925 non-null  float64
 60  share_global_cumulative_flaring_co2        11089 non-null  float64
 61  share_global_cumulative_gas_co2            15167 non-null  float64
 62  share_global_cumulative_luc_co2            37450 non-null  float64
 63  share_global_cumulative_oil_co2            23833 non-null  float64
 64  share_global_cumulative_other_co2          2170 non-null   float64
 65  share_global_flaring_co2                   11089 non-null  float64
 66  share_global_gas_co2                       15167 non-null  float64
 67  share_global_luc_co2                       37450 non-null  float64
 68  share_global_oil_co2                       23833 non-null  float64
 69  share_global_other_co2                     2170 non-null   float64
 70  share_of_temperature_change_from_ghg       41238 non-null  float64
 71  temperature_change_from_ch4                38280 non-null  float64
 72  temperature_change_from_co2                41238 non-null  float64
 73  temperature_change_from_ghg                41238 non-null  float64
 74  temperature_change_from_n2o                38280 non-null  float64
 75  total_ghg                                  38150 non-null  float64
 76  total_ghg_excluding_lucf                   37813 non-null  float64
 77  trade_co2                                  4712 non-null   float64
 78  trade_co2_share                            4712 non-null   float64
dtypes: float64(76), int64(1), object(2)
memory usage: 30.4+ MB
Info sur DataFrame co2
 None

In [20]:
print("Info sur DataFrame GDP \n", df_gdp.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            151 non-null    float64
 5   1961            154 non-null    float64
 6   1962            156 non-null    float64
 7   1963            156 non-null    float64
 8   1964            156 non-null    float64
 9   1965            162 non-null    float64
 10  1966            163 non-null    float64
 11  1967            167 non-null    float64
 12  1968            168 non-null    float64
 13  1969            168 non-null    float64
 14  1970            190 non-null    float64
 15  1971            191 non-null    float64
 16  1972            191 non-null    float64
 17  1973            191 non-null    float64
 18  1974            191 non-null    float64
 19  1975            195 non-null    float64
 20  1976            195 non-null    float64
 21  1977            198 non-null    float64
 22  1978            197 non-null    float64
 23  1979            198 non-null    float64
 24  1980            208 non-null    float64
 25  1981            208 non-null    float64
 26  1982            209 non-null    float64
 27  1983            209 non-null    float64
 28  1984            211 non-null    float64
 29  1985            213 non-null    float64
 30  1986            213 non-null    float64
 31  1987            220 non-null    float64
 32  1988            223 non-null    float64
 33  1989            223 non-null    float64
 34  1990            240 non-null    float64
 35  1991            241 non-null    float64
 36  1992            242 non-null    float64
 37  1993            243 non-null    float64
 38  1994            244 non-null    float64
 39  1995            247 non-null    float64
 40  1996            247 non-null    float64
 41  1997            249 non-null    float64
 42  1998            250 non-null    float64
 43  1999            250 non-null    float64
 44  2000            252 non-null    float64
 45  2001            253 non-null    float64
 46  2002            257 non-null    float64
 47  2003            257 non-null    float64
 48  2004            257 non-null    float64
 49  2005            257 non-null    float64
 50  2006            258 non-null    float64
 51  2007            258 non-null    float64
 52  2008            259 non-null    float64
 53  2009            261 non-null    float64
 54  2010            261 non-null    float64
 55  2011            262 non-null    float64
 56  2012            260 non-null    float64
 57  2013            260 non-null    float64
 58  2014            261 non-null    float64
 59  2015            260 non-null    float64
 60  2016            259 non-null    float64
 61  2017            259 non-null    float64
 62  2018            259 non-null    float64
 63  2019            259 non-null    float64
 64  2020            258 non-null    float64
 65  2021            258 non-null    float64
 66  2022            257 non-null    float64
 67  2023            251 non-null    float64
 68  2024            240 non-null    float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), object(4)
memory usage: 145.6+ KB
Info sur DataFrame GDP
 None

In [6]:
print("Info sur DataFrame Population \n", df_pop.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            264 non-null    float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            264 non-null    float64
 8   1964            264 non-null    float64
 9   1965            264 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            265 non-null    float64
 67  2023            265 non-null    float64
 68  2024            265 non-null    float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), object(4)
memory usage: 145.6+ KB
Info sur DataFrame Population
 None

In [17]:
print("Info sur DataFrame Electricity \n", df_access.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            107 non-null    float64
 35  1991            118 non-null    float64
 36  1992            135 non-null    float64
 37  1993            149 non-null    float64
 38  1994            155 non-null    float64
 39  1995            162 non-null    float64
 40  1996            174 non-null    float64
 41  1997            182 non-null    float64
 42  1998            191 non-null    float64
 43  1999            199 non-null    float64
 44  2000            259 non-null    float64
 45  2001            259 non-null    float64
 46  2002            260 non-null    float64
 47  2003            260 non-null    float64
 48  2004            260 non-null    float64
 49  2005            260 non-null    float64
 50  2006            260 non-null    float64
 51  2007            262 non-null    float64
 52  2008            262 non-null    float64
 53  2009            263 non-null    float64
 54  2010            263 non-null    float64
 55  2011            263 non-null    float64
 56  2012            263 non-null    float64
 57  2013            263 non-null    float64
 58  2014            263 non-null    float64
 59  2015            263 non-null    float64
 60  2016            263 non-null    float64
 61  2017            263 non-null    float64
 62  2018            263 non-null    float64
 63  2019            263 non-null    float64
 64  2020            263 non-null    float64
 65  2021            263 non-null    float64
 66  2022            263 non-null    float64
 67  2023            263 non-null    float64
 68  2024            0 non-null      float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), object(4)
memory usage: 145.6+ KB
Info sur DataFrame Electricity
 None

EDA - Analyse des Entités (Pays vs Régions)

In [ ]:
# Identification des entités qui n'ont pas de Code ISO dans energy mix (Agrégats/Régions)
entites_sans_code_energy = df_energy[df_energy['Code'].isnull()]['Entity'].unique()

print("Entités sans Code ISO dans Energy Mix (Régions ou Groupes) :")
print(entites_sans_code_energy)

Entités sans Code ISO dans Energy Mix (Régions ou Groupes) :
['Africa' 'Africa (EI)' 'Asia' 'Asia Pacific (EI)' 'CIS (EI)'
 'Central America (EI)' 'Eastern Africa (EI)' 'Europe' 'Europe (EI)'
 'European Union (27)' 'High-income countries' 'Low-income countries'
 'Lower-middle-income countries' 'Middle Africa (EI)' 'Middle East (EI)'
 'Non-OECD (EI)' 'North America' 'North America (EI)' 'OECD (EI)'
 'Oceania' 'Other Asia Pacific (EI)' 'Other CIS (EI)'
 'Other Caribbean (EI)' 'Other Europe (EI)' 'Other Middle East (EI)'
 'Other Northern Africa (EI)' 'Other South America (EI)'
 'Other Southern Africa (EI)' 'South America'
 'South and Central America (EI)' 'Upper-middle-income countries'
 'Western Africa (EI)']

In [8]:
# Identification des entités sans iso_code dans le dataset CO2
entites_sans_code_co2 = df_co2[df_co2['iso_code'].isnull()]['country'].unique()

print("Entités sans iso_code dans CO2 Data :")
print(entites_sans_code_co2)

Entités sans iso_code dans CO2 Data :
['Africa' 'Africa (GCP)' 'Asia' 'Asia (GCP)'
 'Asia (excl. China and India)' 'Central America (GCP)' 'Europe'
 'Europe (GCP)' 'Europe (excl. EU-27)' 'Europe (excl. EU-28)'
 'European Union (27)' 'European Union (28)' 'High-income countries'
 'International aviation' 'International shipping' 'Kosovo'
 'Kuwaiti Oil Fires' 'Kuwaiti Oil Fires (GCP)'
 'Least developed countries (Jones et al.)' 'Low-income countries'
 'Lower-middle-income countries' 'Middle East (GCP)' 'Non-OECD (GCP)'
 'North America' 'North America (GCP)' 'North America (excl. USA)'
 'OECD (GCP)' 'OECD (Jones et al.)' 'Oceania' 'Oceania (GCP)'
 'Ryukyu Islands' 'Ryukyu Islands (GCP)' 'South America'
 'South America (GCP)' 'Upper-middle-income countries' 'World']

In [21]:
# Aperçu des noms des pays et groupes dans le dataset GDP
print("Exemple de noms d'entités dans GDP (20 premières) :")
print(df_gdp['Country Name'].unique()[:20])

Exemple de noms d'entités dans GDP (20 premières) :
['Aruba' 'Africa Eastern and Southern' 'Afghanistan'
 'Africa Western and Central' 'Angola' 'Albania' 'Andorra' 'Arab World'
 'United Arab Emirates' 'Argentina' 'Armenia' 'American Samoa'
 'Antigua and Barbuda' 'Australia' 'Austria' 'Azerbaijan' 'Burundi'
 'Belgium' 'Benin' 'Burkina Faso']

In [7]:
# Vérification de la cohérence des noms dans Population
print("Exemple de noms d'entités dans Population (20 premières) :")
print(df_pop['Country Name'].unique()[:20])

Exemple de noms d'entités dans Population (20 premières) :
['Aruba' 'Africa Eastern and Southern' 'Afghanistan'
 'Africa Western and Central' 'Angola' 'Albania' 'Andorra' 'Arab World'
 'United Arab Emirates' 'Argentina' 'Armenia' 'American Samoa'
 'Antigua and Barbuda' 'Australia' 'Austria' 'Azerbaijan' 'Burundi'
 'Belgium' 'Benin' 'Burkina Faso']

In [18]:
# Vérification des noms dans Electricity Access
print("Exemple de noms d'entités dans Electricity Access (20 premières) :")
print(df_access['Country Name'].unique()[:20])

Exemple de noms d'entités dans Electricity Access (20 premières) :
['Aruba' 'Africa Eastern and Southern' 'Afghanistan'
 'Africa Western and Central' 'Angola' 'Albania' 'Andorra' 'Arab World'
 'United Arab Emirates' 'Argentina' 'Armenia' 'American Samoa'
 'Antigua and Barbuda' 'Australia' 'Austria' 'Azerbaijan' 'Burundi'
 'Belgium' 'Benin' 'Burkina Faso']

EDA - Analyse de la Couverture Temporelle

In [34]:
# Vérification de la période pour Energy Mix
print(f"Energy Mix - Année min : {df_energy['Year'].min()}")
print(f"Energy Mix - Année max : {df_energy['Year'].max()}")

# Nombre d'enregistrements par année
print("\nNombre de pays par année (Energy Mix) :")
print(df_energy['Year'].value_counts().sort_index().tail(20))

Energy Mix - Année min : 1965
Energy Mix - Année max : 2024

Nombre de pays par année (Energy Mix) :
Year
2005    139
2006    139
2007    140
2008    140
2009    140
2010    140
2011    140
2012    141
2013    141
2014    141
2015    141
2016    141
2017    141
2018    141
2019    141
2020    141
2021    141
2022    141
2023    141
2024    141
Name: count, dtype: int64

In [9]:
# Vérification de la période pour CO2
print(f"CO2 Data - Année min : {df_co2['year'].min()}")
print(f"CO2 Data - Année max : {df_co2['year'].max()}")

# Nombre d'enregistrements par année
print("\nNombre de pays par année (CO2) :")
print(df_co2['year'].value_counts().sort_index().tail(20))

CO2 Data - Année min : 1750
CO2 Data - Année max : 2024

Nombre de pays par année (CO2) :
year
2005    254
2006    254
2007    254
2008    254
2009    254
2010    254
2011    254
2012    254
2013    254
2014    254
2015    254
2016    254
2017    254
2018    254
2019    254
2020    254
2021    254
2022    254
2023    254
2024    254
Name: count, dtype: int64

In [22]:
# Identifier les colonnes d'années présentes dans le fichier GDP
colonnes_annees_gdp = [col for col in df_gdp.columns if col.isdigit()]
print(f"GDP - Première année : {min(colonnes_annees_gdp)}")
print(f"GDP - Dernière année : {max(colonnes_annees_gdp)}")

# Vérifier combien de pays ont des données pour la dernière année (2023 ou 2024)
derniere_annee_gdp = max(colonnes_annees_gdp)
print(f"\nNombre de valeurs non-nulles en {derniere_annee_gdp} (GDP) :")
print(df_gdp[derniere_annee_gdp].notnull().sum())

GDP - Première année : 1960
GDP - Dernière année : 2024

Nombre de valeurs non-nulles en 2024 (GDP) :
240

In [8]:
# Analyse similaire pour Population
colonnes_annees_pop = [col for col in df_pop.columns if col.isdigit()]
derniere_annee_pop = max(colonnes_annees_pop)

print(f"Population - Période : {min(colonnes_annees_pop)} à {derniere_annee_pop}")
print(f"Nombre de valeurs non-nulles en {derniere_annee_pop} (Population) :")
print(df_pop[derniere_annee_pop].notnull().sum())

Population - Période : 1960 à 2024
Nombre de valeurs non-nulles en 2024 (Population) :
265

In [19]:
# Analyse similaire pour Electricity Access
colonnes_annees_acc = [col for col in df_access.columns if col.isdigit()]
derniere_annee_acc = max(colonnes_annees_acc)

print(f"Access Electricity - Période : {min(colonnes_annees_acc)} à {derniere_annee_acc}")
print(f"Nombre de valeurs non-nulles en {derniere_annee_acc} (Access) :")
print(df_access[derniere_annee_acc].notnull().sum())

Access Electricity - Période : 1960 à 2024
Nombre de valeurs non-nulles en 2024 (Access) :
0

Nettoyage dataset énergie mix

In [40]:
# Renommer la colonne 'Entity' en 'Country'
df_energy = df_energy.rename(columns={'Entity': 'Country'})

# Affichage pour vérifier le changement
df_energy.head(2)

,Country,Code,Year,Oil,Gas,Coal,Hydropower,Solar,Wind,Nuclear,Other renewables
0,Africa,NaN,1965,341.07257,9.571930,323.49615,13.905635,0.0,0.0,0.0,0.0
1,Africa,NaN,1966,369.46457,10.698092,323.12222,15.510004,0.0,0.0,0.0,0.0

In [ ]:
# Supprimer les lignes où le 'Code' est manquant (les agrégats)
# On crée une nouvelle variable 'df_energy_clean' pour garder l'originale intacte au cas où
df_energy_clean = df_energy.dropna(subset=['Code']).copy()

# Vérification s'il reste des codes vides
print(f"Nombre de lignes après filtrage : {len(df_energy_clean)}")
print("Nombre de valeurs manquantes dans 'Code' :", df_energy_clean['Code'].isnull().sum())

Nombre de lignes après filtrage : 5939
Nombre de valeurs manquantes dans 'Code' : 0

In [42]:
# Remplacer les NaN par 0 dans les colonnes de production d'énergie
energy_cols = ['Oil', 'Gas', 'Coal', 'Hydropower', 'Solar', 'Wind', 'Nuclear', 'Other renewables']

df_energy_clean[energy_cols] = df_energy_clean[energy_cols].fillna(0)

# Vérification que tout est à zéro ou rempli
print("Vérification des NaN après traitement :")
print(df_energy_clean[energy_cols].isnull().sum())

Vérification des NaN après traitement :
Oil                 0
Gas                 0
Coal                0
Hydropower          0
Solar               0
Wind                0
Nuclear             0
Other renewables    0
dtype: int64

In [43]:
# Aperçu final du dataset clean
print("Dimensions finales :", df_energy_clean.shape)
df_energy_clean.head(10)

Dimensions finales : (5939, 11)

,Country,Code,Year,Oil,Gas,Coal,Hydropower,Solar,Wind,Nuclear,Other renewables
120,Algeria,DZA,1965,15.405252,7.430500,0.81410,0.400,0.0,0.0,0.0,0.0
121,Algeria,DZA,1966,20.272705,7.719250,0.79084,0.355,0.0,0.0,0.0,0.0
122,Algeria,DZA,1967,18.942032,7.488250,0.60476,0.410,0.0,0.0,0.0,0.0
123,Algeria,DZA,1968,20.167301,7.873250,0.63965,0.563,0.0,0.0,0.0,0.0
124,Algeria,DZA,1969,21.305931,10.351687,0.81410,0.361,0.0,0.0,0.0,0.0
125,Algeria,DZA,1970,24.347680,9.730875,0.96529,0.580,0.0,0.0,0.0,0.0
126,Algeria,DZA,1971,27.440050,11.049499,0.26749,0.330,0.0,0.0,0.0,0.0
127,Algeria,DZA,1972,30.121414,12.830126,0.23260,0.495,0.0,0.0,0.0,0.0
128,Algeria,DZA,1973,32.900345,17.859186,0.26749,0.752,0.0,0.0,0.0,0.0
129,Algeria,DZA,1974,36.543840,20.674500,0.22097,0.497,0.0,0.0,0.0,0.0

In [44]:
# Reset de l'index pour que ça commence de 0 
df_energy_clean = df_energy_clean.reset_index(drop=True)

# Affichage pour voir le nouvel index
df_energy_clean.head(5)

,Country,Code,Year,Oil,Gas,Coal,Hydropower,Solar,Wind,Nuclear,Other renewables
0,Algeria,DZA,1965,15.405252,7.430500,0.81410,0.400,0.0,0.0,0.0,0.0
1,Algeria,DZA,1966,20.272705,7.719250,0.79084,0.355,0.0,0.0,0.0,0.0
2,Algeria,DZA,1967,18.942032,7.488250,0.60476,0.410,0.0,0.0,0.0,0.0
3,Algeria,DZA,1968,20.167301,7.873250,0.63965,0.563,0.0,0.0,0.0,0.0
4,Algeria,DZA,1969,21.305931,10.351687,0.81410,0.361,0.0,0.0,0.0,0.0

In [45]:
# Sauvegarde du dataframe nettoyé 
# On utilise index=False pour ne pas enregistrer la colonne d'index
df_energy_clean.to_csv('../Data_Clean/energy_mix_clean.csv', index=False)

print("Le fichier energy_mix_clean.csv a été enregistré avec succès dans Data_Clean !")

Le fichier energy_mix_clean.csv a été enregistré avec succès dans Data_Clean !

Nettoyage dataset CO2

In [10]:
#Sélection et Renommage
# Sélection des colonnes utiles et renommage pour la cohérence
cols_to_keep = ['country', 'year', 'iso_code', 'co2', 'co2_per_capita', 'coal_co2', 'gas_co2', 'oil_co2']

df_co2_clean = df_co2[cols_to_keep].copy()

# Renommer pour matcher avec df_energy_clean
df_co2_clean = df_co2_clean.rename(columns={
    'country': 'Country',
    'year': 'Year',
    'iso_code': 'Code'
})

df_co2_clean.head()

       Country  Year Code  co2  co2_per_capita  coal_co2  gas_co2  oil_co2
0  Afghanistan  1750  AFG  NaN             NaN       NaN      NaN      NaN
1  Afghanistan  1751  AFG  NaN             NaN       NaN      NaN      NaN
2  Afghanistan  1752  AFG  NaN             NaN       NaN      NaN      NaN
3  Afghanistan  1753  AFG  NaN             NaN       NaN      NaN      NaN
4  Afghanistan  1754  AFG  NaN             NaN       NaN      NaN      NaN

In [12]:
#Filtrage des Pays
# Garder uniquement les pays (Code ISO non null)
df_co2_clean = df_co2_clean.dropna(subset=['Code']).copy()

print(f"Nombre de lignes après filtrage des pays : {len(df_co2_clean)}")

Nombre de lignes après filtrage des pays : 42480

In [13]:
#Imputation par zéro et Index
# Remplacer les NaN par 0 pour les émissions
emissions_cols = ['co2', 'co2_per_capita', 'coal_co2', 'gas_co2', 'oil_co2']
df_co2_clean[emissions_cols] = df_co2_clean[emissions_cols].fillna(0)

# Reset index
df_co2_clean = df_co2_clean.reset_index(drop=True)

# Vérification finale
print("Valeurs manquantes après nettoyage :\n", df_co2_clean.isnull().sum())
df_co2_clean.head()

Valeurs manquantes après nettoyage :
 Country           0
Year              0
Code              0
co2               0
co2_per_capita    0
coal_co2          0
gas_co2           0
oil_co2           0
dtype: int64

       Country  Year Code  co2  co2_per_capita  coal_co2  gas_co2  oil_co2
0  Afghanistan  1750  AFG  0.0             0.0       0.0      0.0      0.0
1  Afghanistan  1751  AFG  0.0             0.0       0.0      0.0      0.0
2  Afghanistan  1752  AFG  0.0             0.0       0.0      0.0      0.0
3  Afghanistan  1753  AFG  0.0             0.0       0.0      0.0      0.0
4  Afghanistan  1754  AFG  0.0             0.0       0.0      0.0      0.0

In [14]:
# Sauvegarde du fichier CO2 nettoyé
df_co2_clean.to_csv('../Data_Clean/co2_clean.csv', index=False)

print("Le fichier co2_clean.csv a été enregistré avec succès dans Data_Clean !")

Le fichier co2_clean.csv a été enregistré avec succès dans Data_Clean !

Nettoyage de dataset GDP

In [23]:
# Identifier les colonnes d'années (celles qui sont numériques)
annees = [col for col in df_gdp.columns if col.isdigit()]

# Utiliser pd.melt pour transformer les colonnes d'années en lignes
df_gdp_long = pd.melt(df_gdp, 
                      id_vars=['Country Name', 'Country Code'], 
                      value_vars=annees, 
                      var_name='Year', 
                      value_name='GDP')

# Convertir Year en entier (int) pour le futur merge
df_gdp_long['Year'] = df_gdp_long['Year'].astype(int)

print(f"Dimensions après Melt : {df_gdp_long.shape}")
df_gdp_long.head()

Dimensions après Melt : (17290, 4)

                  Country Name Country Code  Year           GDP
0                        Aruba          ABW  1960           NaN
1  Africa Eastern and Southern          AFE  1960  2.420569e+10
2                  Afghanistan          AFG  1960           NaN
3   Africa Western and Central          AFW  1960  1.190481e+10
4                       Angola          AGO  1960           NaN

In [24]:
# Renommer les colonnes pour la cohérence
df_gdp_clean = df_gdp_long.rename(columns={
    'Country Name': 'Country',
    'Country Code': 'Code'
})

# Supprimer les lignes où le GDP est NaN (facultatif mais recommandé pour alléger)
df_gdp_clean = df_gdp_clean.dropna(subset=['GDP']).copy()

# Reset index
df_gdp_clean = df_gdp_clean.reset_index(drop=True)

print(f"Dimensions finales du GDP : {df_gdp_clean.shape}")
df_gdp_clean.head()

Dimensions finales du GDP : (14561, 4)

                       Country Code  Year           GDP
0  Africa Eastern and Southern  AFE  1960  2.420569e+10
1   Africa Western and Central  AFW  1960  1.190481e+10
2                    Argentina  ARG  1960  1.586547e+10
3                    Australia  AUS  1960  1.863568e+10
4                      Austria  AUT  1960  6.624086e+09

In [ ]:
# Sauvegarde du fichier gdp nettoyé
df_gdp_clean.to_csv('../Data_Clean/gdp_clean.csv', index=False)

print("Le fichier gdp_clean.csv a été enregistré avec succès dans Data_Clean !")

Le fichier gdp_clean.csv a été enregistré avec succès dans Data_Clean !

Nettoyage de dataset Pupulation

Identification des années et Pivotement (Melt)

In [9]:
# Identify year columns (those that are numeric)
years_pop = [col for col in df_pop.columns if col.isdigit()]

# Transform the dataframe from wide to long format
df_pop_long = pd.melt(df_pop, 
                      id_vars=['Country Name', 'Country Code'], 
                      value_vars=years_pop, 
                      var_name='Year', 
                      value_name='Population')

# Preview the result
df_pop_long.head()

                  Country Name Country Code  Year   Population
0                        Aruba          ABW  1960      54922.0
1  Africa Eastern and Southern          AFE  1960  130075728.0
2                  Afghanistan          AFG  1960    9035043.0
3   Africa Western and Central          AFW  1960   97630925.0
4                       Angola          AGO  1960    5231654.0

Renomage et Nettoyage des types

In [10]:
# Rename columns for consistency with other datasets
df_pop_clean = df_pop_long.rename(columns={
    'Country Name': 'Country',
    'Country Code': 'Code'
})

# Convert Year to integer
df_pop_clean['Year'] = df_pop_clean['Year'].astype(int)

# Drop rows with missing population values to keep it clean
df_pop_clean = df_pop_clean.dropna(subset=['Population']).reset_index(drop=True)

# Final check of dimensions
print(f"Final Population Shape: {df_pop_clean.shape}")
df_pop_clean.head()

Final Population Shape: (17195, 4)

                       Country Code  Year   Population
0                        Aruba  ABW  1960      54922.0
1  Africa Eastern and Southern  AFE  1960  130075728.0
2                  Afghanistan  AFG  1960    9035043.0
3   Africa Western and Central  AFW  1960   97630925.0
4                       Angola  AGO  1960    5231654.0

Sauvegarde du fichier

In [11]:
# Save to CSV in the Data_Clean folder
df_pop_clean.to_csv('../Data_Clean/population_clean.csv', index=False)

print("Le fichier population_clean.csv a été enregistré avec succès dans Data_Clean !")

Le fichier population_clean.csv a été enregistré avec succès dans Data_Clean !

Nettoyage de dataset electricity access

In [20]:
# Melting (Transformation)
# Identify year columns
years_acc = [col for col in df_access.columns if col.isdigit()]

# Pivot the table from wide to long
df_acc_long = pd.melt(df_access, 
                      id_vars=['Country Name', 'Country Code'], 
                      value_vars=years_acc, 
                      var_name='Year', 
                      value_name='Electricity_Access')

df_acc_long.head()

                  Country Name Country Code  Year  Electricity_Access
0                        Aruba          ABW  1960                 NaN
1  Africa Eastern and Southern          AFE  1960                 NaN
2                  Afghanistan          AFG  1960                 NaN
3   Africa Western and Central          AFW  1960                 NaN
4                       Angola          AGO  1960                 NaN

In [21]:
# Cleaning and Filtering
# Rename columns for consistency
df_acc_clean = df_acc_long.rename(columns={
    'Country Name': 'Country',
    'Country Code': 'Code'
})

# Convert Year to integer
df_acc_clean['Year'] = df_acc_clean['Year'].astype(int)

# VERY IMPORTANT: Drop NaN values (this removes the empty years like 1960-1989)
df_acc_clean = df_acc_clean.dropna(subset=['Electricity_Access']).reset_index(drop=True)

# Final check of the remaining data
print(f"Final Access Data Shape: {df_acc_clean.shape}")
df_acc_clean.head()

Final Access Data Shape: (7859, 4)

                Country Code  Year  Electricity_Access
0                 Aruba  ABW  1990            100.0000
1               Albania  ALB  1990            100.0000
2               Andorra  AND  1990            100.0000
3  United Arab Emirates  ARE  1990            100.0000
4             Argentina  ARG  1990             92.1548

In [22]:
# Sauvegarde du fichier
df_acc_clean.to_csv('../Data_Clean/electricity_clean.csv', index=False)

print("Le fichier electricity_clean.csv a été enregistré avec succès dans Data_Clean!")

Le fichier electricity_clean.csv a été enregistré avec succès dans Data_Clean!